spring.application.name=estoque

# Configuração da Porta do Servidor
server.port=8080

# URL do Banco de Dados MySQL (cria o banco 'estoque' automaticamente caso não exista)
spring.datasource.url=jdbc:mysql://localhost:3306/estoque?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false